// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ProjetoMenuWeb.Domain.Context;
using System;

namespace ProjetoMenuWeb.Domain.Migrations
{
    [DbContext(typeof(ProjetoMenuWebContext))]
    [Migration("20180404174618_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetoMenuWeb.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount")
                        .HasColumnName("Quantidade");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnName("Marca")
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("Code")
                        .HasColumnName("Codigo");

                    b.Property<DateTime>("Date")
                        .HasColumnName("Data");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("Descrição")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnName("Modelo")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnName("Valor");

                    b.Property<decimal>("Total")
                        .HasColumnName("Total");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
